version: "3.9"

services:
  product_service:
    build:
      context: ./product_service
    container_name: product_service
    command: daphne config.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - ./product_service/:/product_service/
      - static_volume:/product_service/static
      - media_volume:/product_service/media
    ports:
      - 8001:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - ./.env

  order_service:
    build:
      context: ./order_service
    container_name: order_service
    command: uvicorn apps.orders.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./order_service/:/order_service/
    ports:
      - 8002:8000
    env_file:
      - ./.env

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysql_db_data:/var/lib/mysql:rw
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_db_data:
  static_volume:
  media_volume:
  rabbitmq_data: