version: "3.9"

services:
  product_service:
    build:
      context: ./product_service
    container_name: product_service
    volumes:
      - ./product_service/:/product_service/
      - static_volume:/product_service/static
      - media_volume:/product_service/media
    ports:
      - 8001:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - ./.env

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysql_db_data:/var/lib/mysql:rw
    env_file:
      - ./.env

volumes:
  mysql_db_data:
  static_volume:
  media_volume: